In [1]:
import cv2

In [2]:
# membaca image
image = cv2.imread("004.jpg")

In [3]:
print(image)

[[[255 253 253]
  [255 253 253]
  [255 253 253]
  ...
  [255 253 253]
  [255 253 253]
  [255 253 253]]

 [[255 253 253]
  [255 253 253]
  [255 253 253]
  ...
  [255 253 253]
  [255 253 253]
  [255 253 253]]

 [[255 253 253]
  [255 253 253]
  [255 253 253]
  ...
  [255 253 253]
  [255 253 253]
  [255 253 253]]

 ...

 [[255 253 253]
  [255 253 253]
  [255 253 253]
  ...
  [255 253 253]
  [255 253 253]
  [255 253 253]]

 [[255 253 253]
  [255 253 253]
  [255 253 253]
  ...
  [255 253 253]
  [255 253 253]
  [255 253 253]]

 [[255 253 253]
  [255 253 253]
  [255 253 253]
  ...
  [255 253 253]
  [255 253 253]
  [255 253 253]]]


In [4]:
# menampilkan image
cv2.imshow('leaf', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print(image.shape)

(1200, 1600, 3)


In [6]:
# mengakeses nilai di pixel x=100, y=20
(b, g, r) = image[20, 100]
print("blue =" ,b)
print("green =" ,g)
print("red =" ,r)

blue = 255
green = 253
red = 253


In [7]:
# crop image
im_crop = image[100:660, 100:300]

cv2.imshow('crop' ,im_crop)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(im_crop.shape)

(560, 200, 3)


In [8]:
# mengcopy image
cp_image = image.copy()
print(cp_image.shape)

(1200, 1600, 3)


In [9]:
# mengubah nilai pixel
cp_image[300:350, 170:300] = (255, 255, 255)

cv2.imshow('cp_image' ,cp_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# resize image (ignore aspect ratio)
im_resized = cv2.resize(image, (400,400))

cv2.imshow('im_resize' ,im_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [11]:
# resize image (Mempertahankan aspek ratio)
r = 400/image.shape[1]
dim = (400, int(image.shape[0]*r))
im_resized = cv2.resize(image, dim)

cv2.imshow('im_resized',im_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# rotating an image
(h, w) = image.shape[:2]
center = (w/2, h/2)

M = cv2.getRotationMatrix2D(center, 180, 1.0)
rotate = cv2.warpAffine(image, M, (w,h))

cv2.imshow('rotate',rotate)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# menyimpan Image
cv2.imwrite("rotate.png", rotate)

True

In [14]:
#adjust image contrast
import numpy as np
im_adjusted = cv2.addWeighted(im_resized, 1.5, np.zeros(im_resized.shape, im_resized.dtype), 0, -100)


cv2.imshow('Original Image',im_resized)
cv2.imshow('Adjusted Image',im_adjusted)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
# detect edges
im_edges = cv2.Canny(im_resized, 100, 200)

cv2.imshow('Original Image',im_resized)
cv2.imshow('Detected Edges',im_edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# covert image to greyscale
im_gray = cv2.cvtColor(im_resized, cv2.COLOR_BGR2GRAY)

cv2.imshow('Original Image',im_resized)
cv2.imshow('Grayscale Image',im_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
#get All file in folder
import glob

imdir = 'dataset/elephant/'
ext = ['png', 'jpg', 'gif']    # Add image formats here

files = []
[files.extend(glob.glob(imdir + '*.' + e)) for e in ext]
  
images = [cv2.imread(file) for file in files]
  
# adjust contrast to all of them nd save to different location
i = 1
for img in images:
    im_adjusted = cv2.addWeighted(img, 1.5, np.zeros(img.shape, img.dtype), 0, -100)
    im_name = "dataset/elephant_contrast/" + str(i) + ".jpg"
    cv2.imwrite(im_name, im_adjusted)
    i+=1